server:
  port: 8081


## RedisTemplate使用 https://blog.csdn.net/lydms/article/details/105224210
#spring:
#  redis:
#    host: 192.168.113.62
#    port: 6380
#    database: 0 # redis数据库索引
#    password:
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#        max-wait: -1ms # 连接池最大阻塞时间，负值表示没有限制
#    timeout: 5000ms

spring:
  application:
    name: redis-cluster
  redis:
    cluster:
      nodes: 192.168.113.62:6371,192.168.113.62:6372,192.168.113.62:6373,192.168.113.62:6374,192.168.113.62:6375,192.168.113.62:6376
      max-redirects: 6
redis:
  timeout: 10000 #客户端超时时间单位是毫秒 默认是2000
  maxIdle: 300 #最大空闲数
  maxTotal: 1000 #控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性
  maxWaitMillis: 1000 #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
  minEvictableIdleTimeMillis: 300000 #连接的最小空闲时间 默认1800000毫秒(30分钟)
  numTestsPerEvictionRun: 1024 #每次释放连接的最大数目,默认3
  timeBetweenEvictionRunsMillis: 30000 #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
  testOnBorrow: true #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
  testWhileIdle: true #在空闲时检查有效性, 默认false
  password: 1234 #密码